version: '3.7'
services:
  db:
    image: postgres:14.5-alpine
    container_name: sistema-votacao
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}